[global]
showWarningOnDirectExecution = true

[logger]
level = "debug"

[runner]
magicEnabled = true

[server]
folderWatchBlacklist = ['']
headless = false
runOnSave = true
port = 8501
enableCORS = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501